// Generated by CoffeeScript 1.7.1

/**
 * 
 * @date: 2014-02-23 10:55:29
 * @author: vfasky (vfasky@gmail.com)
 * @link: http://vfasky.com
 * @version: $Id$
 */

(function() {
  var sinon, swig;

  swig = require('../hollow/swigext');

  sinon = require('sinon');

  describe('module', function() {
    return describe('staticUrl', function() {
      return it('css url', function() {
        return 't' === 't';
      });
    });
  });

}).call(this);
