// Generated by CoffeeScript 1.7.1

/**
 * Hollow 配置文件 
 * 使用时，请 `mv config.default.js config.js`
 * @date: 2014-02-22 10:48:42
 * @author: vfasky (vfasky@gmail.com)
 * @link: http://vfasky.com
 * @version: $Id$
 */

(function() {
  exports.staticHost = '127.0.0.1';

  exports.host = '127.0.0.1';

  exports.sessionSecret = 'hollow_catke';

  exports.authCookieName = 'hollow_catke';

  exports.equelizeHost = 'localhost';

  exports.equelizePort = 5432;

  exports.equelizeMaxCon = 100;

  exports.equelizeDialect = 'postgres';

  exports.equelizeDatabase = 'hollow';

  exports.equelizeUsername = 'hollow';

  exports.equelizePassword = '';

  exports.equelizePool = {
    maxConnections: 5,
    maxIdleTime: 30
  };

}).call(this);
