// Generated by CoffeeScript 1.7.1

/**
 * Hollow 配置文件 
 * 使用时，请 `mv config.default.js config.js`
 * @date: 2014-02-22 10:48:42
 * @author: vfasky (vfasky@gmail.com)
 * @link: http://vfasky.com
 * @version: $Id$
 */

(function() {
  var pkg;

  pkg = require('./package.json');

  exports.static_host = '';

  exports.host = '127.0.0.1';

  exports.session_secret = 'hollow_catke';

  exports.auth_cookie_name = 'hollow_catke';

  exports.equelize_host = 'localhost';

  exports.equelize_port = 5432;

  exports.equelize_max_con = 100;

  exports.equelize_dialect = 'postgres';

  exports.equelize_database = 'hollow';

  exports.equelize_username = 'hollow';

  exports.equelize_password = '098765';

  exports.equelize_pool = {
    maxConnections: 5,
    maxIdleTime: 30
  };

}).call(this);

