// Generated by CoffeeScript 1.7.1

/**
 * 首页 
 * @date: 2014-02-28 23:06:49
 * @author: vfasky (vfasky@gmail.com)
 * @link: http://vfasky.com
 * @version: $Id$
 */

(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Express'
    });
  };

}).call(this);
