// Generated by CoffeeScript 1.7.1

/**
 * session Table 
 * @date: 2014-03-04 21:41:55
 * @author: vfasky (vfasky@gmail.com)
 * @link: http://vfasky.com
 * @version: $Id$
 */

(function() {
  var Sequelize;

  Sequelize = require('sequelize');

  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Session', {
      sid: {
        type: DataTypes.STRING,
        primaryKey: true
      },
      data: DataTypes.TEXT
    });
  };

}).call(this);
