// Generated by CoffeeScript 1.7.1

/**
 * @module models
 * @date: 2014-02-22 11:31:01
 * @author: vfasky (vfasky@gmail.com)
 * @link: http://vfasky.com
 * @version: $Id$
 *
 * 存放所有 model 定义
 * @desc
 * ## demo: 
 * 
 * ```coffee
 * database = require './models'
 *
 * database.User.findAll().success (users) ->
 *     console.log users
 *
 * ```
 *
 */

(function() {
  var Sequelize, config, database, fs, lodash, path, sequelize,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  fs = require('fs');

  path = require('path');

  config = require('../config');

  Sequelize = require('sequelize');

  lodash = require('lodash');

  database = {};


  /**
   * 返回实例化的 Sequelize
   * @module models/sequelize
   */

  sequelize = new Sequelize(config.equelizeDatabase, config.equelizeUsername, config.equelizePassword, {
    dialect: config.equelizeDialect,
    host: config.equelizeHost,
    port: config.equelizePort,
    maxConcurrentQueries: config.equelizeMaxCon,
    pool: config.equelizePool
  });

  fs.readdirSync(__dirname).filter(function(file) {
    return file.indexOf('.coffee') === -1 && file.indexOf('.') !== 0 && file !== 'index.js';
  }).forEach(function(file) {
    var model;
    model = sequelize["import"](path.join(__dirname, file));
    return database[model.name] = model;
  });

  Object.keys(database).forEach(function(modelName) {
    if (__indexOf.call(database[modelName], 'associate') >= 0) {
      return database[modelName].associate(database);
    }
  });

  module.exports = lodash.extend({
    sequelize: sequelize,
    Sequelize: Sequelize
  }, database);

}).call(this);
